export enum RoleCode {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INITIATOR = 'INITIATOR',
  APPROVER = 'APPROVER',
  PAYMENTS_MAKER = 'PAYMENTS_MAKER',
  PAYMENTS_CHECKER = 'PAYMENTS_CHECKER',
  FINANCE_HEAD = 'FINANCE_HEAD',
}
